version: '3'
services:

  server:
    container_name: express-server
    build: ./server/
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    links:
      - mongo
  client:
    container_name: react-frontend
    build: ./client/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - server
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"