version: '3'
services:

  backend:
    container_name: express-backend
    build: ./backend/
    ports:
      - "80:3000"
    volumes:
      - ./backend:/usr/src/app
    links:
      - mongo
  frontend:
    container_name: react-frontend
    build: ./client/
    ports:
      - "3001:3001"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"